@startuml

package "src/main/kotlin/programmer/zaman/now/kotlin/restful" {
    package "entity" {
        class Product {
            +id: String
            +name: String
            +price: Long
            +quantity: Int
            +createdAt: Date
            +updatedAt: Date?
        }
    }

    package "model" {
        class CreateProductRequest {
            +name: String
            +price: Long
            +quantity: Int
        }

        class ProductResponse {
            +id: String
            +name: String
            +price: Long
            +quantity: Int
            +createdAt: Date
            +updatedAt: Date?
        }

        class WebResponse<T> {
            +code: Int
            +status: String
            +data: T
        }
    }

    package "repository" {
        interface ProductRepository
        ProductRepository <|-- Product
    }

    package "service" {
        interface ProductService
        class ProductServiceImpl
        
        ProductService --> ProductRepository
        ProductService --> Product
        ProductServiceImpl --> ProductService
    }

    package "controller" {

        class ProductController
        
        ProductController --> ProductService
    }
}

ProductController -down-> ProductService : uses
ProductService -down-> ProductRepository : uses
ProductRepository -down-> Product : manages

@enduml