@startuml

package "src/main/kotlin/programmer/zaman/now/kotlin/restful" {
    package "1. entity" {
        class Product {
            +id: String
            +name: String
            +price: Long
            +quantity: Int
            +createdAt: Date
            +updatedAt: Date?
        }
    }

    package "2. model" {
        class CreateProductRequest {
            +name: String
            +price: Long
            +quantity: Int
        }

        class ProductResponse {
            +id: String
            +name: String
            +price: Long
            +quantity: Int
            +createdAt: Date
            +updatedAt: Date?
        }

        class WebResponse<T> {
            +code: Int
            +status: String
            +data: T
        }
    }

    package "3. repository" {
        interface ProductRepository {
            +save(product: Product): Product 
        }
    }

    package "4. service dan IMPL" {
        interface ProductService {
            +create(request: CreateProductRequest): ProductResponse
        }
        
        class ProductServiceImpl
        
        ProductService --> ProductRepository
        ProductService --> Product
        ProductServiceImpl --> ProductService
    }

    package "5. controller" {
        class ProductController {
            +create(request: CreateProductRequest): WebResponse<ProductResponse>
        }
    }

    package "6. database" {
        class ProductTable {
            +id: String (PK)
            +name: String
            +price: Long
            +quantity: Int
            +created_at: Timestamp
            +updated_at: Timestamp
        }
    }
}

ProductController -down-> ProductService : uses
ProductService -down-> ProductRepository : uses
ProductRepository -down-> Product : manages
ProductRepository -down-> ProductTable : interacts

ProductController --> CreateProductRequest : uses
ProductController --> WebResponse : uses
ProductController --> ProductResponse : uses
ProductService --> CreateProductRequest : uses
ProductService --> ProductResponse : uses
ProductServiceImpl --> CreateProductRequest : uses
ProductServiceImpl --> ProductResponse : uses

@enduml